name: Build

on:
  push:
    branches: [ main, Lab2_Tests ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd lab_2 && make 

    - name: Test
      run: cd lab_2 && go mod tidy && make test
      
    - name: Clean
      run: cd lab_2 && make clean
